# Dependabot will run on day 23 of each month at 01:16 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "16 1 23 * *"
    open-pull-requests-limit: 20
    assignees:
      - "UncleSamSwiss"
    versioning-strategy: "increase"
